name: hkdf
description: An implementation of the symmetric HMAC-based Key Derivation Function (HKDF) mechanism. (RFC 5869)
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.5

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
