name: hkdf
description: An implementation of the symmetric HMAC-based Key Derivation Function (HKDF) mechanism. (RFC 5869)
version: 1.0.1
repository: https://github.com/carlosmakin/hkdf

environment:
  sdk: ^3.3.0

dependencies:
  crypto: ^3.0.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2
